<?php
require_once 'vendor/autoload.php'; // Mengimpor autoload dari Composer

// Create new PDF document
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Name');
$pdf->SetTitle('Laporan Uang Keluar Inventaris');
$pdf->SetSubject('Laporan Uang Keluar Inventaris');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// Set default header data
$pdf->SetHeaderData('', 0, 'Laporan Uang Keluar Inventaris', 'Generated by TCPDF');

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Add a page
$pdf->AddPage();

// Set font
$pdf->SetFont('helvetica', '', 12);

// Include the database connection
include('db_connect.php');

// SQL query to select data from the view
$query = "SELECT id_inventaris, nama_barang, satuan, uang_keluar, total_uang_keluar_satuan FROM laporan_uang_keluar_inventaris";
$stmt = $pdo->query($query);

// Initialize total accumulator
$totalUangKeluarSatuan = 0;

// Create table header
$html = '<h2>Laporan Uang Keluar Inventaris</h2>';
$html .= '<table border="1" cellpadding="5">
            <thead>
                <tr>
                    <th>ID Inventaris</th>
                    <th>Nama Barang</th>
                    <th>Satuan</th>
                    <th>Uang Keluar</th>
                    <th>Total Uang Keluar Satuan</th>
                </tr>
            </thead>
            <tbody>';

// Fetch and display the data
while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
    // Accumulate total
    $totalUangKeluarSatuan += $row['total_uang_keluar_satuan'];

    // Add row to the table
    $html .= '<tr>
                <td>' . htmlspecialchars($row['id_inventaris']) . '</td>
                <td>' . htmlspecialchars($row['nama_barang']) . '</td>
                <td>' . htmlspecialchars($row['satuan']) . '</td>
                <td>' . htmlspecialchars($row['uang_keluar']) . '</td>
                <td>' . htmlspecialchars($row['total_uang_keluar_satuan']) . '</td>
              </tr>';
}

// Close table and add total row
$html .= '</tbody>
          <tfoot>
            <tr>
              <td colspan="4" style="text-align: right;"><strong>Total</strong></td>
              <td><strong>' . number_format($totalUangKeluarSatuan, 2) . '</strong></td>
            </tr>
          </tfoot>
          </table>';

// Output the HTML content
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('laporan_uang_keluar_inventaris.pdf', 'I');

// Close connection
$pdo = null;
?>
